image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

go-build:
  image: golang:1.12
  stage: build
  script: "go build -o users"
  artifacts:
    paths:
      - users

docker-build:
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker-hub.informatik.haw-hamburg.de
  - docker build -t docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/users .
  - docker push docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/users
  tags: [dind, docker]

cloud-deploy:
  stage: deploy
  environment:
    name: Dev
  image: microsoft/azure-cli
  script:
    # setup kubectl
    - curl -LO $K8S_STABLE_VERSION_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - touch ~/.kube/config
    - export KUBECONFIG=$KUBECONFIG:~/.kube/config
    # connect to azure k8s
    - az login --service-principal --username $AZ_USERNAME --password $AZ_PASSWORD --tenant $AZ_TENANT_ID
    - az aks get-credentials --resource-group $AZ_RESOURCE_GROUP --name $AZ_CLUSTER_NAME
    - kubectl config use-context $AZ_CLUSTER_NAME
    # deploy new image!
    - kubectl -n default rollout restart deployment/users-svc