image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  #-deploy

maven-build:
  image: golang:1.9
  stage: build
  script: "go build -o users"
  artifacts:
    paths:
      - users

docker-build:
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker-hub.informatik.haw-hamburg.de
  - docker build -t docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/users .
  - docker push docker-hub.informatik.haw-hamburg.de/wp-cc-clouddrop/users